server:
  port: 8888

spring:
  application:
    name: gomall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
#        - id: route_baidu
#          uri: http://www.baidu.com
#          predicates:
#            - Query=url, baidu
#        - id: qq_route
#          uri: https://www.qq.com/
#          predicates:
#            - Query=url, qq
        - id: product_route
          uri: lb://gomall-product
          predicates:
            - Path=/api/product/**,/hello
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: third_party_route
          uri: lb://gomall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>/?.*),/$\{segment}

        - id: gomall-member
          uri: lb://gomall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: ware_route
          uri: lb://gomall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast #lb表示负载均衡
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}
        # 域名服务接口
        - id: gomall_host_route
          uri: lb://gomall-product
          predicates:
            - Host=gomall.com,item.gomall.com

        - id: gomall_search_route
          uri: lb://gomall-search
          predicates:
            - Host=search.gomall.com

        - id: gomall_auth_route
          uri: lb://gomall-auth-server
          predicates:
            - Host=auth.gomall.com

        - id: gomall_cart_route
          uri: lb://gomall-cart
          predicates:
            - Host=cart.gomall.com
