server:
  port: 8888

spring:
  application:
    name: gomall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
#        - id: route_baidu
#          uri: http://www.baidu.com
#          predicates:
#            - Query=url, baidu
#        - id: qq_route
#          uri: https://www.qq.com/
#          predicates:
#            - Query=url, qq
        - id: product_route
          uri: lb://gomall-product
          predicates:
            - Path=/api/product/**,/hello
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: third_party_route
          uri: lb://gomall-third-party
          predicates:
            - Path=/api/thirdparty/**
          filters:
            - RewritePath=/api/thirdparty/(?<segment>/?.*),/$\{segment}

        - id: member_route
          uri: lb://gomall-member
          predicates:
            - Path=/api/member/**
          filters:
            - RewritePath=/api/(?<segment>/?.*),/$\{segment}

        - id: order_route
          uri: lb://gomall-order
          predicates:
            - Path=/api/order/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: coupon_route
          uri: lb://gomall-coupon
          predicates:
            - Path=/api/coupon/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: ware_route
          uri: lb://gomall-ware
          predicates:
            - Path=/api/ware/**
          filters:
            - RewritePath=/api/(?<segment>.*),/$\{segment}

        - id: admin_route
          uri: lb://renren-fast #lb表示负载均衡
          predicates:
            - Path=/api/**
          filters:
            - RewritePath=/api/(?<segment>/?.*), /renren-fast/$\{segment}
        # 域名服务接口
        - id: gomall_host_route
          uri: lb://gomall-product
          predicates:
            - Host=gomall.com,item.gomall.com

        - id: gomall_search_route
          uri: lb://gomall-search
          predicates:
            - Host=search.gomall.com

        - id: gomall_auth_route
          uri: lb://gomall-auth-server
          predicates:
            - Host=auth.gomall.com

        - id: gomall_cart_route
          uri: lb://gomall-cart
          predicates:
            - Host=cart.gomall.com

        - id: gomall_order_route
          uri: lb://gomall-order
          predicates:
            - Host=order.gomall.com

        - id: gomall_member_route
          uri: lb://gomall-member
          predicates:
            - Host=member.gomall.com

        - id: gomall_seckill_route
          uri: lb://gomall-seckill
          predicates:
            - Host=seckill.gomall.com



## 前端项目请求路径 都带/api
## 前端请求路径 http://localhost:88/api/captcha.jpg?uuid=1a0d6a79-28b4-43e0-8e59-0d1b4d5c0f83
## 后端实际路径 http://localhost:88/renren-fast/captcha.jpg?uuid=1a0d6a79-28b4-43e0-8e59-0d1b4d5c0f83

## 前端 http://localhost:88/api/product/category/list/tree
## 后端商品服务 http://localhost:88/product/category/list/tree

# http://localhost:8888/api/ware/wareinfo/list?

# zipkin 配置
  zipkin:
    base-url: http://192.168.108.131:9411/
    discovery-client-enabled: false
    sender: web
  sleuth:
    sampler:
      probability: 1
